#!/bin/bash

set -x
set -e

if [ -z "${TRAVIS_TAG}" ]; then
  export TRAVIS_TAG=$(date -u +%s)
fi

export TIMESTAMP=$TRAVIS_TAG
echo $TIMESTAMP > .timestamp

dnf install -y rpm-build make
make -C /mnt srpm
