#!/bin/bash

set -x
set -e

cd /mnt

TRAVIS_TAG=$(cat .timestamp)
TIMESTAMP=$(cat .timestamp)

dnf install -y git copr-cli

srpm=$(ls numix-999-${TRAVIS_TAG}*.src.rpm)

install -m 0700 -d ${HOME}/.ssh
cat > ${HOME}/.ssh/config <<EOF
Host github.com
  User git
  IdentityFile /mnt/secrets/id_rsa.github
  CheckHostIP no
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
EOF

install -D /mnt/secrets/copr ${HOME}/.config/copr

git config user.name "numixproject"
git config user.email "ci@numixproject.org"
git remote remove origin
git remote add origin git@github.com:sspreitzer/numix-specs.git
git reset --hard ${TRAVIS_TAG}
git fetch
git checkout gh-pages
make
git add index.html ${srpm}
git commit -m "add srpm ${TRAVIS_TAG}"
for tag in $(git tag | grep -v ${TRAVIS_TAG}); do
  git push origin :${tag}
done
git push origin gh-pages
sleep 20
copr build --nowait numix/numix http://sspreitzer.github.io/numix-specs/${srpm}
